### ISSUE TITLE
comment in index refers to non existent file

### ISSUE THREAD

**Issue by Ethanjfobrien** [StartBootstrap/startbootstrap-business-frontpage#1]
the comment regarding the header background image refers to a file "business-casual.css" which is not in the repository

**Comment by davidtmiller** [comment]
Ancient development artifacts! Fun fact, this template was originally named Business Casual, but I scrapped that title for later use. Nice catch on this one. I'll update it in the next patch.

**Comment by Ethanjfobrien** [comment]
Cheers, it's a nice template!
