### ISSUE TITLE
Best method for copying template if you want to make repo private?

### ISSUE THREAD

**Issue by w4rner** [StartBootstrap/startbootstrap-business-frontpage#18]
<img width="772" alt="image" src="https://user-images.githubusercontent.com/31451410/68997220-a5888f80-0869-11ea-824a-0c2d1b58b037.png">
1). Should I just static download the files & build upon them in a new private repo? Are there any benefits to forking, e.g. if you improve the base codebase would I be able to update mine?
2). Do you think it is best practise to make the codebase repo for a client website private? Given that users can just inspect the codebase anyway, are there actually any downsides to it being left public?
Thanks for thoughts folks,
w4rner

**Comment by w4rner** [comment]
Any ideas @BlackrockDigital ?

**Comment by davidtmiller** [comment]
You could fork the repo and make your fork private, or you could download the zip files, create your own repo, and then make that repo private. That should work just fine for the purpose of making something private. Hopefully this helps!

**Comment by davidtmiller** [comment]
This template is now a template repository, so you can create a new repo using this template rather than forking it!
